# Use the official Node.js image
FROM node:14

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code to the working directory
COPY . .

ENV PORT=3000

# Expose the port on which the application will run
EXPOSE 3000

# Command to run the application
CMD ["npm", "run", "dev"]
