version: "3.8"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"

  api:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"